#chat netty 配置
chat:
  port: 9001 #netty 端口
  max-content-length: 10000
  message-persistence: false
  encryption: false
  needAuthorization: false
  tokenName: 'token'

logging:
  level:
    com.ratel: DEBUG

